---

- name: Reapply ACL to Guest VLAN
  cisco.ios.ios_config:
    lines: ip access-group Guest-ACL in
    parents: interface Vlan{{ guest_vlan.stdout[0].split()[0] }}
    match: exact

- name: Reapply ACL to Camera VLAN
  cisco.ios.ios_config:
    lines: ip access-group Security-Cameras-ACL out
    parents: interface Vlan{{ camera_vlan.stdout[0].split()[0] }}
    match: exact

- name: Reapply ACL to Relay VLAN
  cisco.ios.ios_config:
    lines: ip access-group Production-ACL in
    parents: interface Vlan{{ relay_vlan.stdout[0].split()[0] }}
    match: exact

- name: Reapply ACL to Inline VLAN
  cisco.ios.ios_config:
    lines: ip access-group Production-ACL in
    parents: interface Vlan{{ inline_vlan.stdout[0].split()[0] }}
    match: exact

- name: Reapply ACL to Mgmt VLAN
  cisco.ios.ios_config:
    lines: ip access-group BldgMgmt-ACL in
    parents: interface Vlan{{ mgmt_vlan.stdout[0].split()[0] }}
    match: exact

...